name: trashcare
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.2
  page_transition: ^2.1.0
  animated_bottom_navigation_bar: ^1.3.0
  avatar_glow: 2.0.0
  file_selector_windows: 0.9.3+1
  http: ^1.1.0
  flutter: 
    sdk: flutter
  dio: ^5.4.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - images/
    - bot_responses.json
  uses-material-design: true

